"""Commit message

Revision ID: 887ca82e5770
Revises: 3ddb763db202
Create Date: 2020-09-09 16:19:47.969647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887ca82e5770'
down_revision = '3ddb763db202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'accept_policy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accept_policy', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
